[Rule]
# Spotify blocks
URL-REGEX,^https?:\/\/([^\/]+\.)?spotify\.com\/gabo-receiver-service,REJECT
URL-REGEX,^https?:\/\/([^\/]+\.)?spotify\.com\/ad-logic,REJECT
URL-REGEX,^https?:\/\/([^\/]+\.)?spotify\.com\/ads,REJECT

# Reddit block
URL-REGEX,^https?:\/\/([^\/]+\.)?reddit\.com\/svc\/shreddit\/events,REJECT
