[Rule]
# Spotify blocks
URL-REGEX,^https?:\/\/([^\/]+\.)?spotify\.com\/gabo-receiver-service,REJECT
URL-REGEX,^https?:\/\/([^\/]+\.)?spotify\.com\/ad-logic,REJECT
URL-REGEX,^https?:\/\/([^\/]+\.)?spotify\.com\/ads,REJECT
URL-REGEX,^https?:\/\/([^\/]+\.)?spotify\.com\/sponsoredplaylist,REJECT

# Reddit block
URL-REGEX,^https?:\/\/([^\/]+\.)?reddit\.com\/svc\/shreddit\/events,REJECT

# Zalo and related analytics blocks
URL-REGEX,^https?:\/\/([^\/]+\.)?zalo\.video\/vsocial,REJECT
URL-REGEX,^https?:\/\/h5\.zadn\.vn\/static\/analytics,REJECT
URL-REGEX,^https?:\/\/h5\.zalo\.me\/log\/async,REJECT
URL-REGEX,^https?:\/\/channel-zinstant\.api\.zaloapp\.com\/api\/channel\/zinstant-data,REJECT
